//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StealthLibrary.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StealthBaseEntities : DbContext
    {
        public StealthBaseEntities()
            : base("name=StealthBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Questionnaire> tbl_Questionnaire { get; set; }
        public DbSet<tbl_QuestionnaireCategory> tbl_QuestionnaireCategory { get; set; }
    }
}
