//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StealthLibrary.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Questionnaire
    {
        public int QuestionID { get; set; }
        public Nullable<int> QuestionCategory { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string QuestionNote { get; set; }
        public Nullable<byte> Point { get; set; }
        public Nullable<bool> SubQuestion { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<bool> IsChild { get; set; }
        public string ParentID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool Inactive { get; set; }
        public bool Deleted { get; set; }
    }
}
